# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/v1/example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65xample/v1/example.proto\x12\x10proto.example.v1\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0c\x45\x63hoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\" \n\x10GetRecordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"P\n\x11GetRecordResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x03(\t2\xad\x01\n\x0e\x45xampleService\x12\x45\n\x04\x45\x63ho\x12\x1d.proto.example.v1.EchoRequest\x1a\x1e.proto.example.v1.EchoResponse\x12T\n\tGetRecord\x12\".proto.example.v1.GetRecordRequest\x1a#.proto.example.v1.GetRecordResponseB:Z8github.com/ryapric/workshops/protobuf-grpc/pb/example/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.v1.example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8github.com/ryapric/workshops/protobuf-grpc/pb/example/v1'
  _ECHOREQUEST._serialized_start=46
  _ECHOREQUEST._serialized_end=72
  _ECHORESPONSE._serialized_start=74
  _ECHORESPONSE._serialized_end=101
  _GETRECORDREQUEST._serialized_start=103
  _GETRECORDREQUEST._serialized_end=135
  _GETRECORDRESPONSE._serialized_start=137
  _GETRECORDRESPONSE._serialized_end=217
  _EXAMPLESERVICE._serialized_start=220
  _EXAMPLESERVICE._serialized_end=393
# @@protoc_insertion_point(module_scope)
