# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/v1/example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example/v1/example.proto',
  package='proto.example.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x18\x65xample/v1/example.proto\x12\x10proto.example.v1\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0c\x45\x63hoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\" \n\x10GetRecordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"P\n\x11GetRecordResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x03(\t2\xaf\x01\n\x0e\x45xampleService\x12G\n\x04\x45\x63ho\x12\x1d.proto.example.v1.EchoRequest\x1a\x1e.proto.example.v1.EchoResponse\"\x00\x12T\n\tGetRecord\x12\".proto.example.v1.GetRecordRequest\x1a#.proto.example.v1.GetRecordResponseB:Z8github.com/ryapric/workshops/protobuf-grpc/pb/example/v1b\x06proto3')
)




_ECHOREQUEST = _descriptor.Descriptor(
  name='EchoRequest',
  full_name='proto.example.v1.EchoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto.example.v1.EchoRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=72,
)


_ECHORESPONSE = _descriptor.Descriptor(
  name='EchoResponse',
  full_name='proto.example.v1.EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto.example.v1.EchoResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=101,
)


_GETRECORDREQUEST = _descriptor.Descriptor(
  name='GetRecordRequest',
  full_name='proto.example.v1.GetRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.example.v1.GetRecordRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=135,
)


_GETRECORDRESPONSE = _descriptor.Descriptor(
  name='GetRecordResponse',
  full_name='proto.example.v1.GetRecordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.example.v1.GetRecordResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.example.v1.GetRecordResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='proto.example.v1.GetRecordResponse.birthday', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='proto.example.v1.GetRecordResponse.details', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['EchoRequest'] = _ECHOREQUEST
DESCRIPTOR.message_types_by_name['EchoResponse'] = _ECHORESPONSE
DESCRIPTOR.message_types_by_name['GetRecordRequest'] = _GETRECORDREQUEST
DESCRIPTOR.message_types_by_name['GetRecordResponse'] = _GETRECORDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), dict(
  DESCRIPTOR = _ECHOREQUEST,
  __module__ = 'example.v1.example_pb2'
  # @@protoc_insertion_point(class_scope:proto.example.v1.EchoRequest)
  ))
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), dict(
  DESCRIPTOR = _ECHORESPONSE,
  __module__ = 'example.v1.example_pb2'
  # @@protoc_insertion_point(class_scope:proto.example.v1.EchoResponse)
  ))
_sym_db.RegisterMessage(EchoResponse)

GetRecordRequest = _reflection.GeneratedProtocolMessageType('GetRecordRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRECORDREQUEST,
  __module__ = 'example.v1.example_pb2'
  # @@protoc_insertion_point(class_scope:proto.example.v1.GetRecordRequest)
  ))
_sym_db.RegisterMessage(GetRecordRequest)

GetRecordResponse = _reflection.GeneratedProtocolMessageType('GetRecordResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRECORDRESPONSE,
  __module__ = 'example.v1.example_pb2'
  # @@protoc_insertion_point(class_scope:proto.example.v1.GetRecordResponse)
  ))
_sym_db.RegisterMessage(GetRecordResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z8github.com/ryapric/workshops/protobuf-grpc/pb/example/v1'))

_EXAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='ExampleService',
  full_name='proto.example.v1.ExampleService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=220,
  serialized_end=395,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='proto.example.v1.ExampleService.Echo',
    index=0,
    containing_service=None,
    input_type=_ECHOREQUEST,
    output_type=_ECHORESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRecord',
    full_name='proto.example.v1.ExampleService.GetRecord',
    index=1,
    containing_service=None,
    input_type=_GETRECORDREQUEST,
    output_type=_GETRECORDRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLESERVICE)

DESCRIPTOR.services_by_name['ExampleService'] = _EXAMPLESERVICE

# @@protoc_insertion_point(module_scope)
