# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import example_pb2 as example_dot_v1_dot_example__pb2


class ExampleServiceStub(object):
  """Allow for service annotations, if needed. Check commented-out lines on each relevant service below
  import "google/api/annotations.proto";

  Service that shows a few ways to work with protobufs and gRPC
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/proto.example.v1.ExampleService/Echo',
        request_serializer=example_dot_v1_dot_example__pb2.EchoRequest.SerializeToString,
        response_deserializer=example_dot_v1_dot_example__pb2.EchoResponse.FromString,
        )
    self.GetRecord = channel.unary_unary(
        '/proto.example.v1.ExampleService/GetRecord',
        request_serializer=example_dot_v1_dot_example__pb2.GetRecordRequest.SerializeToString,
        response_deserializer=example_dot_v1_dot_example__pb2.GetRecordResponse.FromString,
        )


class ExampleServiceServicer(object):
  """Allow for service annotations, if needed. Check commented-out lines on each relevant service below
  import "google/api/annotations.proto";

  Service that shows a few ways to work with protobufs and gRPC
  """

  def Echo(self, request, context):
    """option (google.api.http) = {
    get: "/api"
    };
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExampleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=example_dot_v1_dot_example__pb2.EchoRequest.FromString,
          response_serializer=example_dot_v1_dot_example__pb2.EchoResponse.SerializeToString,
      ),
      'GetRecord': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecord,
          request_deserializer=example_dot_v1_dot_example__pb2.GetRecordRequest.FromString,
          response_serializer=example_dot_v1_dot_example__pb2.GetRecordResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.example.v1.ExampleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
