# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from example.v1 import example_pb2 as example_dot_v1_dot_example__pb2


class ExampleServiceStub(object):
    """Service that shows a few ways to work with protobufs and gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/proto.example.v1.ExampleService/Echo',
                request_serializer=example_dot_v1_dot_example__pb2.EchoRequest.SerializeToString,
                response_deserializer=example_dot_v1_dot_example__pb2.EchoResponse.FromString,
                )
        self.GetRecord = channel.unary_unary(
                '/proto.example.v1.ExampleService/GetRecord',
                request_serializer=example_dot_v1_dot_example__pb2.GetRecordRequest.SerializeToString,
                response_deserializer=example_dot_v1_dot_example__pb2.GetRecordResponse.FromString,
                )


class ExampleServiceServicer(object):
    """Service that shows a few ways to work with protobufs and gRPC
    """

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=example_dot_v1_dot_example__pb2.EchoRequest.FromString,
                    response_serializer=example_dot_v1_dot_example__pb2.EchoResponse.SerializeToString,
            ),
            'GetRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecord,
                    request_deserializer=example_dot_v1_dot_example__pb2.GetRecordRequest.FromString,
                    response_serializer=example_dot_v1_dot_example__pb2.GetRecordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.example.v1.ExampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExampleService(object):
    """Service that shows a few ways to work with protobufs and gRPC
    """

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.example.v1.ExampleService/Echo',
            example_dot_v1_dot_example__pb2.EchoRequest.SerializeToString,
            example_dot_v1_dot_example__pb2.EchoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.example.v1.ExampleService/GetRecord',
            example_dot_v1_dot_example__pb2.GetRecordRequest.SerializeToString,
            example_dot_v1_dot_example__pb2.GetRecordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
