# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pb/example.proto\"\x17\n\x08\x45\x63hoable\x12\x0b\n\x03msg\x18\x01 \x01(\t\" \n\x10GetRecordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"P\n\x11GetRecordResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x03(\t2[\n\x07\x45xample\x12\x1c\n\x04\x45\x63ho\x12\t.Echoable\x1a\t.Echoable\x12\x32\n\tGetRecord\x12\x11.GetRecordRequest\x1a\x12.GetRecordResponseB\x10Z\x0e\x65xample.com/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016example.com/pb'
  _ECHOABLE._serialized_start=20
  _ECHOABLE._serialized_end=43
  _GETRECORDREQUEST._serialized_start=45
  _GETRECORDREQUEST._serialized_end=77
  _GETRECORDRESPONSE._serialized_start=79
  _GETRECORDRESPONSE._serialized_end=159
  _EXAMPLE._serialized_start=161
  _EXAMPLE._serialized_end=252
# @@protoc_insertion_point(module_scope)
